name: Runs Ci for Project
on:
  push:
    branches:
      - master
      - "features/**"
  pull_request:
  workflow_dispatch:
    inputs:
      pythonVersion:
        description: "python version"
        default : 3.2


jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      -uses: actions/checkout@v4
      -name: build test runner docker image
       run: docker compose build test_runner
      -name: Run unit Test Runner
       run: docker compose up --abort-on-container-exit test_runner
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{inputs.pythonVersion}}
    -name: package install 
    run:
      pip install -r requirements.txt 
      pip install pytest
    -name: Run unit test
    run: pytest tests/
  server-build: 
    runs-on: ubuntu-latest
    needs:
      - lint-check
      - unit-test
    steps:
      -uses:actions/checkout@v4