name: Runs Ci for Project
on:
  - push
  - pull_request

jobs:
  lint-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      -name: build test runner docker image
       run: docker compose build test_runner
      -name: Run unit Test Runner
       run: docker compose up --abort-on-container-exit test_runner
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.13' 
    -name: package install 
    run:
      pip install -r requirements.txt 
      pip install pytest
    -name: Run unit test
    run: pytest tests/